ALTER TABLE filmes 
MODIFY titulo VARCHAR(50) NOT NULL,
MODIFY categoria VARCHAR(55) NOT NULL,
MODIFY duracao INT(5) NOT NULL,
MODIFY diretor VARCHAR(100) NOT NULL,
MODIFY ano INT(4) NOT NULL;

ALTER TABLE filmes 
ADD id INT(5) NOT NULL PRIMARY KEY AUTO_INCREMENT
FIRST;